package renderer

import (
	"testing"
)

func TestBuildFootnotes_Empty(t *testing.T) {
	opts := DefaultOptions()
	got := buildFootnotes(opts)
	if got.Enabled {
		t.Fatal("expected Enabled=false for empty footnotes")
	}
	if len(got.Footnotes) != 0 {
		t.Fatalf("expected 0 entries, got %d", len(got.Footnotes))
	}
}

func TestBuildFootnotes_SingleEntry(t *testing.T) {
	opts := DefaultOptions()
	WithFootnote("Generated by CI")(&opts)
	got := buildFootnotes(opts)
	if !got.Enabled {
		t.Fatal("expected Enabled=true")
	}
	if len(got.Footnotes) != 1 {
		t.Fatalf("expected 1 entry, got %d", len(got.Footnotes))
	}
	if got.Footnotes[0].Text != "Generated by CI" {
		t.Errorf("unexpected text: %s", got.Footnotes[0].Text)
	}
	if got.Footnotes[0].Index != 1 {
		t.Errorf("expected index 1, got %d", got.Footnotes[0].Index)
	}
}

func TestBuildFootnotes_MultipleEntries_IndexedCorrectly(t *testing.T) {
	opts := DefaultOptions()
	WithFootnote("First note")(&opts)
	WithFootnote("Second note")(&opts)
	WithFootnote("Third note")(&opts)
	got := buildFootnotes(opts)
	if len(got.Footnotes) != 3 {
		t.Fatalf("expected 3 entries, got %d", len(got.Footnotes))
	}
	for i, e := range got.Footnotes {
		if e.Index != i+1 {
			t.Errorf("entry %d: expected index %d, got %d", i, i+1, e.Index)
		}
	}
}

func TestBuildFootnotes_LimitTruncates(t *testing.T) {
	opts := DefaultOptions()
	WithFootnote("Note A")(&opts)
	WithFootnote("Note B")(&opts)
	WithFootnote("Note C")(&opts)
	WithFootnoteLimit(2)(&opts)
	got := buildFootnotes(opts)
	if len(got.Footnotes) != 2 {
		t.Fatalf("expected 2 entries after limit, got %d", len(got.Footnotes))
	}
	if !got.Truncated {
		t.Error("expected Truncated=true")
	}
	if got.Total != 3 {
		t.Errorf("expected Total=3, got %d", got.Total)
	}
}

func TestBuildFootnotes_LimitZeroMeansUnlimited(t *testing.T) {
	opts := DefaultOptions()
	WithFootnote("A")(&opts)
	WithFootnote("B")(&opts)
	WithFootnoteLimit(0)(&opts)
	got := buildFootnotes(opts)
	if len(got.Footnotes) != 2 {
		t.Fatalf("expected 2 entries, got %d", len(got.Footnotes))
	}
	if got.Truncated {
		t.Error("expected Truncated=false for zero limit")
	}
}

func TestWithFootnote_EmptyIgnored(t *testing.T) {
	opts := DefaultOptions()
	WithFootnote("")(&opts)
	if len(opts.Footnotes) != 0 {
		t.Errorf("expected empty footnotes, got %d entries", len(opts.Footnotes))
	}
}

func TestWithFootnoteLimit_NegativeClampedToZero(t *testing.T) {
	opts := DefaultOptions()
	WithFootnoteLimit(-5)(&opts)
	if opts.FootnoteLimit != 0 {
		t.Errorf("expected FootnoteLimit=0, got %d", opts.FootnoteLimit)
	}
}
