// Package renderer provides HTML report generation for driftctl JSON output.
//
// # Footnotes
//
// The footnote module appends user-defined notes to the bottom of the
// generated report. Footnotes are numbered sequentially starting from 1
// and are rendered in a dedicated section after the main content.
//
// # Usage
//
//	renderer.New(analysis,
//		renderer.WithFootnote("Generated by CI pipeline on main branch"),
//		renderer.WithFootnote("Reviewed by platform team"),
//		renderer.WithFootnoteLimit(10),
//	)
//
// # Limiting
//
// WithFootnoteLimit(n) caps the number of footnotes rendered. A limit of 0
// (the default) means all provided footnotes are included.
//
// Footnotes are rendered in the order they were added via WithFootnote.
package renderer
