package renderer

import "testing"

func TestWithWatermark_SetsText(t *testing.T) {
	o := DefaultOptions()
	WithWatermark("Generated by driftctl-report")(o)
	if o.WatermarkText != "Generated by driftctl-report" {
		t.Fatalf("expected watermark text to be set, got %q", o.WatermarkText)
	}
}

func TestWithWatermark_EmptyClears(t *testing.T) {
	o := DefaultOptions()
	o.WatermarkText = "old"
	WithWatermark("")(o)
	if o.WatermarkText != "" {
		t.Fatalf("expected watermark text to be cleared, got %q", o.WatermarkText)
	}
}

func TestWithWatermark_DefaultIsEmpty(t *testing.T) {
	o := DefaultOptions()
	if o.WatermarkText != "" {
		t.Fatalf("expected default watermark text to be empty, got %q", o.WatermarkText)
	}
}

func TestWithWatermarkURL_SetsURL(t *testing.T) {
	o := DefaultOptions()
	WithWatermarkURL("https://example.com")(o)
	if o.WatermarkURL != "https://example.com" {
		t.Fatalf("expected watermark URL to be set, got %q", o.WatermarkURL)
	}
}

func TestWithWatermarkURL_DefaultIsEmpty(t *testing.T) {
	o := DefaultOptions()
	if o.WatermarkURL != "" {
		t.Fatalf("expected default watermark URL to be empty, got %q", o.WatermarkURL)
	}
}

func TestWithWatermarkPosition_Footer(t *testing.T) {
	o := DefaultOptions()
	WithWatermarkPosition("footer")(o)
	if o.WatermarkPosition != "footer" {
		t.Fatalf("expected position 'footer', got %q", o.WatermarkPosition)
	}
}

func TestWithWatermarkPosition_Header(t *testing.T) {
	o := DefaultOptions()
	WithWatermarkPosition("header")(o)
	if o.WatermarkPosition != "header" {
		t.Fatalf("expected position 'header', got %q", o.WatermarkPosition)
	}
}

func TestWithWatermarkPosition_Both(t *testing.T) {
	o := DefaultOptions()
	WithWatermarkPosition("both")(o)
	if o.WatermarkPosition != "both" {
		t.Fatalf("expected position 'both', got %q", o.WatermarkPosition)
	}
}

func TestWithWatermarkPosition_UnknownIgnored(t *testing.T) {
	o := DefaultOptions()
	o.WatermarkPosition = "footer"
	WithWatermarkPosition("sidebar")(o)
	if o.WatermarkPosition != "footer" {
		t.Fatalf("expected position to remain 'footer', got %q", o.WatermarkPosition)
	}
}

func TestWithWatermarkPosition_EmptyIgnored(t *testing.T) {
	o := DefaultOptions()
	o.WatermarkPosition = "header"
	WithWatermarkPosition("")(o)
	if o.WatermarkPosition != "header" {
		t.Fatalf("expected position to remain 'header', got %q", o.WatermarkPosition)
	}
}
