package renderer

import (
	"testing"
)

func TestWithFootnote_SetsText(t *testing.T) {
	opts := DefaultOptions()
	WithFootnote("Generated by CI pipeline")(opts)
	if len(opts.Footnotes) != 1 {
		t.Fatalf("expected 1 footnote, got %d", len(opts.Footnotes))
	}
	if opts.Footnotes[0] != "Generated by CI pipeline" {
		t.Errorf("unexpected footnote text: %q", opts.Footnotes[0])
	}
}

func TestWithFootnote_EmptyIgnored(t *testing.T) {
	opts := DefaultOptions()
	WithFootnote("")(opts)
	if len(opts.Footnotes) != 0 {
		t.Errorf("expected 0 footnotes, got %d", len(opts.Footnotes))
	}
}

func TestWithFootnote_AccumulatesMultiple(t *testing.T) {
	opts := DefaultOptions()
	WithFootnote("first")(opts)
	WithFootnote("second")(opts)
	WithFootnote("third")(opts)
	if len(opts.Footnotes) != 3 {
		t.Fatalf("expected 3 footnotes, got %d", len(opts.Footnotes))
	}
	if opts.Footnotes[1] != "second" {
		t.Errorf("expected second footnote to be %q, got %q", "second", opts.Footnotes[1])
	}
}

func TestWithFootnoteLimit_PositiveValue(t *testing.T) {
	opts := DefaultOptions()
	WithFootnoteLimit(5)(opts)
	if opts.FootnoteLimit != 5 {
		t.Errorf("expected FootnoteLimit=5, got %d", opts.FootnoteLimit)
	}
}

func TestWithFootnoteLimit_ZeroMeansUnlimited(t *testing.T) {
	opts := DefaultOptions()
	WithFootnoteLimit(0)(opts)
	if opts.FootnoteLimit != 0 {
		t.Errorf("expected FootnoteLimit=0, got %d", opts.FootnoteLimit)
	}
}

func TestWithFootnoteLimit_NegativeClampedToZero(t *testing.T) {
	opts := DefaultOptions()
	WithFootnoteLimit(-3)(opts)
	if opts.FootnoteLimit != 0 {
		t.Errorf("expected FootnoteLimit clamped to 0, got %d", opts.FootnoteLimit)
	}
}

func TestWithFootnoteLimit_DefaultIsZero(t *testing.T) {
	opts := DefaultOptions()
	if opts.FootnoteLimit != 0 {
		t.Errorf("expected default FootnoteLimit=0, got %d", opts.FootnoteLimit)
	}
}
